Daman banner update
navgurukul/soni-sori pull request #183
Opened 2021-11-09 19:53 UTC by damanpreet97

Includes changes to banner component

2021-11-10 11:29 UTC, bsroomy requested changes

2021-11-10 11:29 UTC, bsroomy commented on learn/src/main/java/org/navgurukul/learn/courses/db/models/BaseCourseContent.kt
> +enum class MerakiButtonType {
This should be moved to meraki button class

2021-11-10 11:29 UTC, bsroomy commented on learn/src/main/java/org/navgurukul/learn/ui/common/MerakiButton.kt
> +) : FrameLayout(context, attributes, defaultStyleAttr) {
The parent should be a button, framelayout is useless here

2021-11-10 11:29 UTC, bsroomy commented on learn/src/main/java/org/navgurukul/learn/ui/common/MerakiButton.kt
> +        merakiButton.text = element.label?:"Default"
This method can be added as extension outside this class or simply a method in the class where this method is used

2021-11-10 11:29 UTC, bsroomy commented on learn/src/main/java/org/navgurukul/learn/ui/common/MerakiButton.kt
> +    fun setVariant(variant: MerakiButtonType){
variant should be a property with a getter and a setter (could be kotlin getter setters)

2021-11-10 11:29 UTC, bsroomy commented on learn/src/main/java/org/navgurukul/learn/courses/db/models/BaseCourseContent.kt
> +        var icon: String? = "ic_arrow_right",
Default value should be removed

2021-11-10 11:29 UTC, bsroomy commented on learn/src/main/res/layout/layout_meraki_button.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
This whole file can be removed by making material button as parent of meraki button class

2022-02-18 07:11 UTC, abhishekgupta92 approved these changes

2022-02-18 07:29 UTC, merged