*issue #223 was fixed*
navgurukul/soni-sori pull request #228
Opened 2022-10-23 11:23 UTC by Anurag-Kumar-Mishra

Added a cancelable dialog which will be called when user tries to exit python playground without saving code. Positive button will save code.
Negative button will exit python playground without saving code.

2022-11-13 18:59 UTC, damanpreet97 requested changes

2022-11-13 18:59 UTC, damanpreet97 commented on python/src/main/java/org/navgurukul/playground/editor/PythonEditorFragment.kt
> +                    if(!viewModel.viewState.value!!.fileSaved&&viewModel.viewState.value!!.code.isNotEmpty()) {
viewModel.viewState.value!! could be saved in a variable and reused. Also lets pls add spaces around '&&' to maintain readability

2022-11-13 18:59 UTC, damanpreet97 commented on python/src/main/java/org/navgurukul/playground/editor/PythonEditorFragment.kt
> +        fileNotSavedDialog.setTitle("File not saved")
fileNotSavedDialog.apply {
 setTitle()
 setMessage()
 .
 .
}
You may also use this for a better readability, also looks a bit cleaner this way and saves the redundancy of variable name everytime.

2022-11-13 18:59 UTC, damanpreet97 commented on python/src/main/java/org/navgurukul/playground/editor/PythonEditorFragment.kt
> +            viewModel.viewState.value!!.fileSaved = true
viewModel.viewState.value!! can be reused from the above variable

2022-11-15 03:06 UTC, Anurag-Kumar-Mishra commented
Closing this PR, sending New PR

2022-11-15 03:06 UTC, closed without merging