Internal release
navgurukul/soni-sori pull request #263
Opened 2023-07-17 05:57 UTC by Dhan-shri

Merging all code to Main

2023-08-08 07:02 UTC, Dhan-shri commented on app/build.gradle.kts
> -            buildConfigField("String", "SERVER_URL", "\"https://dev-api.merakilearn.org/\"")
just checked

2023-08-08 07:05 UTC, Dhan-shri commented on app/build.gradle.kts
> +            buildConfigField("String", "SERVER_URL", "\"https://merd-api.merakilearn.org/\"")
hi

2023-08-08 07:17 UTC, damanpreet97 requested changes

2023-08-12 07:14 UTC, Dhan-shri commented on app/src/main/java/org/merakilearn/datasource/network/model/UploadCredentials.kt
> +    val project_id : String
@damanpreet97 Done check once

2023-08-12 07:14 UTC, Dhan-shri commented on app/src/main/java/org/merakilearn/datasource/network/UserUpdateName.kt
> +    val profile_picture:String?
@damanpreet97 Done check once. it is not using any column

2023-08-12 07:14 UTC, Dhan-shri commented on app/src/main/java/org/merakilearn/FileChooserActivity.kt
> +                    scheme.compareTo("https") == 0 -> {
Done check once

2023-08-15 06:48 UTC, damanpreet97 approved these changes

2023-08-15 18:21 UTC, merged