Kalyani synthetic/development
navgurukul/soni-sori pull request #328
Opened 2024-04-15 09:15 UTC by boyakalyani

Clear PR for synthetic to binding changes

2024-04-17 11:29 UTC, surajsahani commented
Make Sure PR passes al CLI checks

2024-05-09 04:15 UTC, surajsahani commented on app/src/main/java/org/merakilearn/MainActivity.kt
> -//        it.setOnClickListener {
Don't remove fake login from here @kalyaniboya

2024-05-09 06:39 UTC, surajsahani requested changes
Please update the requested changes

2024-05-09 06:39 UTC, surajsahani commented on app/src/main/java/org/merakilearn/ui/profile/ProfileFragment.kt
> +        btnCross= requireActivity().findViewById(R.id.btnCross)
remove find view by id here

2024-05-09 06:39 UTC, surajsahani commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val versionCode = 93
This can Bump up after all review. for now discard this changes

2024-05-09 06:39 UTC, surajsahani commented on app/src/main/java/org/merakilearn/ui/profile/ProfileFragment.kt
> +    lateinit var btnCross:ImageView
make this variable private

2024-05-09 06:39 UTC, surajsahani commented on learn/src/main/java/org/navgurukul/learn/ui/learn/ClassFragment.kt
> +        val tvClassTitle = alertLayout.findViewById<TextView>(R.id.tvClassTitle)
replace this line by binding

2024-05-09 06:39 UTC, surajsahani commented on learn/src/main/java/org/navgurukul/learn/ui/learn/ClassFragment.kt
> +        val tvBatchDate = alertLayout.findViewById<TextView>(R.id.tv_Batch_Date)
replace this line with binding

2024-05-09 06:39 UTC, surajsahani commented on commonUI/src/main/java/org/navgurukul/commonui/platform/StateView.kt
> +            if (newState != field) {
Why we can't use state here?

2024-05-09 06:39 UTC, surajsahani commented on learn/src/main/java/org/navgurukul/learn/ui/learn/LearnFragmentPathwaySelectionSheet.kt
> -            if (item.logo?.endsWith(".svg") == true) {
is there no changes in this function?

2024-05-09 06:39 UTC, surajsahani commented on learn/src/main/java/org/navgurukul/learn/ui/learn/LearnLanguageSelectionSheet.kt
> +    lateinit var binding: LearnSelectionSheetBinding
make this field private

2024-05-09 06:39 UTC, surajsahani commented on learn/src/main/res/layout/fragment_class.xml
> +                    android:visibility="gone" />
what is the purpose of removing tools:visibility here?

2024-05-09 06:39 UTC, surajsahani commented on typing/src/main/java/org/navgurukul/typingguru/keyboard/KeyboardActivity.kt
> +            when (event) {
what is purpose of taking event instead of it?

2024-05-09 06:39 UTC, surajsahani commented on app/src/main/java/org/merakilearn/ui/playground/PlaygroundFragment.kt
> +    fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View
@Dhan-shri Please review this interface as well

2024-06-13 13:37 UTC, damanpreet97 approved these changes

2024-06-13 13:48 UTC, damanpreet97 approved these changes

2024-06-15 07:49 UTC, surajsahani approved these changes

2024-06-17 05:35 UTC, surajsahani commented
Looks Good, Merging it now

2024-06-17 05:35 UTC, merged