Development select course api
navgurukul/soni-sori pull request #331
Opened 2024-06-03 07:48 UTC by shainakhatun

first-page course selection

2024-06-03 07:49 UTC, shainakhatun commented
again creating the pr

2024-06-13 13:46 UTC, damanpreet97 requested changes

2024-06-13 13:46 UTC, damanpreet97 commented on app/src/main/java/org/merakilearn/ui/onboarding/OnBoardingViewModel.kt
> +            if (data != null && translations != null) {
use '?.let' in place of null wherever possible

2024-06-13 13:46 UTC, damanpreet97 commented on learn/src/main/java/org/navgurukul/learn/ui/learn/LearnFragmentViewModel.kt
> +            if (completedData != null) {
use '?.let' in place of null

2024-06-13 13:46 UTC, damanpreet97 commented on app/src/main/java/org/merakilearn/ui/onboarding/SelectCourseFragment.kt
> +            if (state.onBoardingData != null && state.onBoardingTranslations != null) {
try to use '?.let' in place of null wherever possible

2026-05-06 14:08 UTC, closed without merging